apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  labels:
    app.kubernetes.io/instance: my-kafka-cluster
    eventstreams.ibm.com/cluster: my-kafka-cluster
  name: testuser
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - host: '*'
        operation: Write
        resource:
          name: TEST
          patternType: literal
          type: topic
    type: simple
